import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import Image from "next/image";
import { Button } from "@repo/ui/button";
import styles from "./page.module.css";
const ThemeImage = (props) => {
    const { srcLight, srcDark, ...rest } = props;
    return (_jsxs(_Fragment, { children: [_jsx(Image, { ...rest, src: srcLight, className: "imgLight" }), _jsx(Image, { ...rest, src: srcDark, className: "imgDark" })] }));
};
export default function Home() {
    return (_jsxs("div", { className: styles.page, children: [_jsxs("main", { className: styles.main, children: [_jsx(ThemeImage, { className: styles.logo, srcLight: "turborepo-dark.svg", srcDark: "turborepo-light.svg", alt: "Turborepo logo", width: 180, height: 38, priority: true }), _jsxs("ol", { children: [_jsxs("li", { children: ["Get started by editing ", _jsx("code", { children: "apps/web/app/page.tsx" })] }), _jsx("li", { children: "Save and see your changes instantly." })] }), _jsxs("div", { className: styles.ctas, children: [_jsxs("a", { className: styles.primary, href: "https://vercel.com/new/clone?demo-description=Learn+to+implement+a+monorepo+with+a+two+Next.js+sites+that+has+installed+three+local+packages.&demo-image=%2F%2Fimages.ctfassets.net%2Fe5382hct74si%2F4K8ZISWAzJ8X1504ca0zmC%2F0b21a1c6246add355e55816278ef54bc%2FBasic.png&demo-title=Monorepo+with+Turborepo&demo-url=https%3A%2F%2Fexamples-basic-web.vercel.sh%2F&from=templates&project-name=Monorepo+with+Turborepo&repository-name=monorepo-turborepo&repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fturborepo%2Ftree%2Fmain%2Fexamples%2Fbasic&root-directory=apps%2Fdocs&skippable-integrations=1&teamSlug=vercel&utm_source=create-turbo", target: "_blank", rel: "noopener noreferrer", children: [_jsx(Image, { className: styles.logo, src: "/vercel.svg", alt: "Vercel logomark", width: 20, height: 20 }), "Deploy now"] }), _jsx("a", { href: "https://turborepo.com/docs?utm_source", target: "_blank", rel: "noopener noreferrer", className: styles.secondary, children: "Read our docs" })] }), _jsx(Button, { appName: "web", className: styles.secondary, children: "Open alert" })] }), _jsxs("footer", { className: styles.footer, children: [_jsxs("a", { href: "https://vercel.com/templates?search=turborepo&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app", target: "_blank", rel: "noopener noreferrer", children: [_jsx(Image, { "aria-hidden": true, src: "/window.svg", alt: "Window icon", width: 16, height: 16 }), "Examples"] }), _jsxs("a", { href: "https://turborepo.com?utm_source=create-turbo", target: "_blank", rel: "noopener noreferrer", children: [_jsx(Image, { "aria-hidden": true, src: "/globe.svg", alt: "Globe icon", width: 16, height: 16 }), "Go to turborepo.com \u2192"] })] })] }));
}
